GET http://localhost:8080/device/?n=chromecast4k

###

GET http://localhost:8080/hello

###

POST http://localhost:8080/device/save
Content-Type: application/json

{
  "deviceName":"HP Laserjet 234"
}

###

GET http://localhost:8080/device/findAll

### jsonP test

GET http://localhost:8080/hello/jsonp

###

GET http://localhost:8080/hello/jsonpXML
Accept: application/xml

###


GET http://localhost:8080/hello/jsonp
Accept: application/json